// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv4aH_tcq7pRi-ebrTVYjPzYc7i0XTeRk',
    appId: '1:425692534531:web:93434ad13cc03b230a3b36',
    messagingSenderId: '425692534531',
    projectId: 'onsip-1f735',
    authDomain: 'onsip-1f735.firebaseapp.com',
    storageBucket: 'onsip-1f735.appspot.com',
    measurementId: 'G-52E48WQLDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEPBTnkK32pMyqBHpIoF6BnNuBZ_HjVJ4',
    appId: '1:425692534531:android:b45d18dc481c3df60a3b36',
    messagingSenderId: '425692534531',
    projectId: 'onsip-1f735',
    storageBucket: 'onsip-1f735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO5AKknYcjk8GxFW1QyfBj_kUrKqzPJWY',
    appId: '1:425692534531:ios:5f73beaaf570bf280a3b36',
    messagingSenderId: '425692534531',
    projectId: 'onsip-1f735',
    storageBucket: 'onsip-1f735.appspot.com',
    iosBundleId: 'com.example.onsip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO5AKknYcjk8GxFW1QyfBj_kUrKqzPJWY',
    appId: '1:425692534531:ios:5f73beaaf570bf280a3b36',
    messagingSenderId: '425692534531',
    projectId: 'onsip-1f735',
    storageBucket: 'onsip-1f735.appspot.com',
    iosBundleId: 'com.example.onsip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv4aH_tcq7pRi-ebrTVYjPzYc7i0XTeRk',
    appId: '1:425692534531:web:a1a2e923a4d82b110a3b36',
    messagingSenderId: '425692534531',
    projectId: 'onsip-1f735',
    authDomain: 'onsip-1f735.firebaseapp.com',
    storageBucket: 'onsip-1f735.appspot.com',
    measurementId: 'G-89Z4R6CLKQ',
  );
}
